import React, { useState } from 'react';
import {
  Sliders,
  FileCode2,
  Copy,
  Check,
  Download,
  CheckCircle2,
  FileText,
  Search,
} from 'lucide-react';
import type { BackendConfigState, VideoAnalysisResult } from '../types';
import { ENV_SPECS, INITIAL_CONFIG, MOCK_VIDEOS } from '../data/mockData';

interface ConfigInspectorProps {
  config?: BackendConfigState;
  currentResult?: VideoAnalysisResult;
}

export const ConfigInspector: React.FC<ConfigInspectorProps> = ({
  config = INITIAL_CONFIG,
  currentResult = MOCK_VIDEOS[0],
}) => {
  const [selectedSchema, setSelectedSchema] = useState<string>('explained_json');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [filterQuery, setFilterQuery] = useState<string>('');

  const schemas: { id: string; name: string; filename: string; content: string }[] = [
    {
      id: 'explained_json',
      name: 'Final Evidence Audit JSON',
      filename: `${currentResult.video_id}_explained.json`,
      content: currentResult.raw_files.explained_json,
    },
    {
      id: 'causal_json',
      name: 'Causal Linkages JSON',
      filename: `${currentResult.video_id}_causal.json`,
      content: currentResult.raw_files.causal_json,
    },
    {
      id: 'verification_json',
      name: 'Hallucination Verification JSON',
      filename: `${currentResult.video_id}_verification.json`,
      content: currentResult.raw_files.verification_json,
    },
    {
      id: 'captions_json',
      name: 'Per-Scene Captions JSON',
      filename: `${currentResult.video_id}_captions.json`,
      content: currentResult.raw_files.captions_json,
    },
    {
      id: 'narrative_txt',
      name: 'Synthesized Narrative Prose',
      filename: `${currentResult.video_id}_narrative.txt`,
      content: currentResult.raw_files.narrative_txt,
    },
    {
      id: 'explained_md',
      name: 'Human-Readable Audit Report',
      filename: `${currentResult.video_id}_explained.md`,
      content: currentResult.raw_files.explained_md,
    },
  ];

  const activeSchema = schemas.find((s) => s.id === selectedSchema) || schemas[0];

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(id);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownload = (filename: string, content: string) => {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filteredEnv = ENV_SPECS.filter(
    (item) =>
      item.key.toLowerCase().includes(filterQuery.toLowerCase()) ||
      item.desc.toLowerCase().includes(filterQuery.toLowerCase())
  );

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-xs font-mono text-indigo-400">
          <Sliders className="w-3.5 h-3.5" />
          <span>RUNTIME SCHEMAS & ENVIRONMENT CONFIGURATION</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-extrabold text-slate-100 mt-1">
          System Configuration & Artifact Inspector
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          Audit JSON schemas, pipeline environment variables, and verification outputs generated by the Veritas pipeline.
        </p>
      </div>

      {/* Artifact Schema Viewer */}
      <section className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-2">
          <div className="flex items-center gap-2">
            <FileCode2 className="w-4 h-4 text-cyan-400" />
            <span className="text-sm font-bold text-slate-200 font-mono">
              Pipeline Stage Artifact Explorer
            </span>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {schemas.map((s) => (
              <button
                key={s.id}
                onClick={() => setSelectedSchema(s.id)}
                className={`px-2.5 py-1 rounded text-xs font-mono transition-all cursor-pointer ${
                  selectedSchema === s.id
                    ? 'bg-indigo-600 text-white font-bold'
                    : 'bg-slate-900/80 text-slate-400 hover:bg-slate-800 hover:text-slate-200'
                }`}
              >
                {s.filename}
              </button>
            ))}
          </div>
        </div>

        {/* Code View Card */}
        <div className="rounded-lg border border-slate-800 bg-slate-950/80 overflow-hidden backdrop-blur-md">
          <div className="px-4 py-2.5 border-b border-slate-800/80 flex items-center justify-between bg-slate-900/60">
            <div className="flex items-center gap-2 font-mono text-xs text-slate-300">
              <FileText className="w-3.5 h-3.5 text-indigo-400" />
              <span>{activeSchema.name}</span>
              <span className="text-slate-500">({activeSchema.filename})</span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => handleCopy(activeSchema.content, activeSchema.id)}
                className="flex items-center gap-1.5 px-2 py-1 rounded text-xs font-mono text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
                title="Copy to clipboard"
              >
                {copiedKey === activeSchema.id ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-400">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy</span>
                  </>
                )}
              </button>

              <button
                onClick={() => handleDownload(activeSchema.filename, activeSchema.content)}
                className="flex items-center gap-1.5 px-2 py-1 rounded text-xs font-mono text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
                title="Download file"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Save</span>
              </button>
            </div>
          </div>

          <div className="p-4 font-mono text-xs leading-relaxed text-slate-300 overflow-x-auto max-h-[420px] custom-scrollbar">
            <pre>
              <code>{activeSchema.content}</code>
            </pre>
          </div>
        </div>
      </section>

      {/* .env Environment Validator List */}
      <section className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-2">
          <div>
            <span className="text-xs font-mono uppercase tracking-wider text-indigo-400 font-semibold">
              Deployment Integrity Check
            </span>
            <h2 className="text-base font-bold text-slate-200 font-mono flex items-center gap-2 mt-1">
              <span>.env Configuration Validator ({ENV_SPECS.length} Parameters)</span>
            </h2>
          </div>

          <div className="relative">
            <Search className="w-4 h-4 absolute left-2.5 top-2.5 text-slate-500" />
            <input
              type="text"
              placeholder="Search env keys..."
              value={filterQuery}
              onChange={(e) => setFilterQuery(e.target.value)}
              className="bg-slate-900/80 border border-slate-700 rounded-md pl-9 pr-3 py-1.5 text-xs font-mono text-slate-200 w-56 focus:border-indigo-500 focus:outline-none"
            />
          </div>
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-900/60 backdrop-blur-md overflow-hidden shadow-lg">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse font-mono text-xs">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/80 text-slate-400 text-[11px] uppercase tracking-wider">
                  <th className="p-3">Variable Key</th>
                  <th className="p-3">Type</th>
                  <th className="p-3">Active Value</th>
                  <th className="p-3">Purpose & Impact</th>
                  <th className="p-3 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/80">
                {filteredEnv.map((env) => {
                  let currentValue = env.sample;
                  if (env.key === 'CAPTIONING_BACKEND') currentValue = config.captioningBackend;
                  if (env.key === 'PY_SCENE_DETECT_THRESHOLD') currentValue = config.pySceneDetectThreshold.toString();
                  if (env.key === 'NUM_FRAMES_PER_SCENE') currentValue = config.numFramesPerScene.toString();
                  if (env.key === 'WHISPER_MODEL_SIZE') currentValue = config.whisperModelSize;
                  if (env.key === 'USE_BATCH_API') currentValue = config.useBatchApi.toString();

                  const isSecret = env.type === 'secret';
                  const displayValue = isSecret ? '••••••••••••••••••••' : currentValue;

                  return (
                    <tr key={env.key} className="hover:bg-slate-800/40 transition-colors">
                      <td className="p-3 font-bold text-cyan-300">
                        {env.key}
                      </td>
                      <td className="p-3 text-slate-400">
                        <span className="px-1.5 py-0.5 rounded bg-slate-800/80 text-[10px]">
                          {env.type}
                        </span>
                      </td>
                      <td className="p-3 text-indigo-300">
                        {displayValue}
                      </td>
                      <td className="p-3 text-slate-300 font-sans max-w-md text-xs">
                        {env.desc}
                      </td>
                      <td className="p-3 text-center">
                        <span className="inline-flex items-center gap-1 text-emerald-400 text-[11px] font-bold">
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          VALID
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </section>
    </div>
  );
};

export default ConfigInspector;
